library(knitr)
library(xtable)
library(printr)
library(effects)
library(car)
library(AER)
library(broom)
library(tseries)

food <-read.csv(file='C:/Users/benzi/OneDrive/Documents/food.csv') 

head(food)

food_exp =food[,1]
income = food[,2]
food = cbind(food,food_exp,income)               

summary(food)

plot(food$income, food$food_exp, 
     ylim=c(0, max(food$food_exp)),
     xlim=c(0, max(food$income)),
     xlab="weekly income in $100", 
     ylab="weekly food expenditure in $", 
     type = "p")

#Linear model
m1 <- lm(food_exp~income, data=food)
b1 <- coef(m1)[[1]]
b2 <- coef(m1)[[2]]
sm1 <- summary(m1)
sm1

#var-covariance matrix
vcv <-vcov(m1) 
vcv
df <-data.frame(vcv)
kable(df, caption="Output generated by the `VCOV` function")

#anova table
anov <- anova(m1)
dfr <- data.frame(anov)
kable(dfr, caption="Output generated by the `anova` function")

dev.off() #to avoid figure margin too large error
##plot 
plot(food$income, food$food_exp, 
     xlab="weekly income in $100", 
     ylab="weekly food expenditure in $", 
     type = "p")
abline(b1,b2)

#Preiction
newx <- data.frame(income = 20)
yhat <- predict(m1, newx)
names(yhat)
yhat
predict(m1, newx, interval="confidence",level=0.95)
predict(m1, newx, interval="prediction",level=0.95)


## B
apt <- data.frame("index" = c(1, 2, 3, 4, 5, 6, 7, 8),
                  "sales" = c(10, 12, 28, 24, 18, 16, 15, 12),
                  "score" = c(55, 60, 85, 75, 80, 85, 65, 60))
apt
m2 <- lm(sales~score, data=apt)
summary(m2)


anov2 <- anova(m2)
anov2
